### ISSUE TITLE
the script extract-kegg.sh depends on CacheControl and lockfile, but they are is not in the requirements-kg2-build.txt file 

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#107]
Error message from `extract-kegg.log`:
```
+ curl -L https://raw.githubusercontent.com/RTXteam/RTX/master/code/reasoningtool/kg-construction/cache_control_helper.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100  1579  100  1579    0     0   9127      0 --:--:-- --:--:-- --:--:--  9127
+ /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/query_kegg.py /home/ubuntu/kg2-build/kegg.json
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/query_kegg.py", line 9, in <module>
    from cache_control_helper import CacheControlHelper
  File "/home/ubuntu/RTX-KG2/cache_control_helper.py", line 2, in <module>
    from cachecontrol.heuristics import BaseHeuristic
ModuleNotFoundError: No module named 'cachecontrol'
```

**Comment by saramsey** [comment]
Need to check `kg2lindsey.rtx.ai` to see what version of `cachecontrol` was being used...

**Comment by saramsey** [comment]
On `kg2lindsey.rtx.ai`:
```
(kg2-venv) ubuntu@ip-172-31-59-26:~$ pip3 freeze | grep Cache
CacheControl==0.12.6
```

**Comment by saramsey** [comment]
Pushed the latest code change to `requirements-kg2-build.txt` to `buildkg2.rtx.ai` and reran:
```
source kg2-venv/bin/activate
pip3 install -r kg2-code/requirements-kg2-build.txt
```
and the `cachecontrol` module seems to work now:
```
(kg2-venv) ubuntu@ip-172-31-63-157:~/kg2-code$ python3
Python 3.7.5 (default, Feb 23 2021, 13:22:40)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cachecontrol
>>>
```

**Comment by saramsey** [comment]
Commit 981e2d0 should fix the lockfile package dependency issue

**Comment by saramsey** [comment]
Ran this on `buildkg2.rtx.ai`:
```
ubuntu@ip-172-31-63-157:~/kg2-code$ source ~/kg2-venv/bin/activate
(kg2-venv) ubuntu@ip-172-31-63-157:~/kg2-code$ pip3 install -r requirements-kg2-build.txt
```
and it looks like it installed lockfile:
```
Installing collected packages: lockfile
Successfully installed lockfile-0.12.2
```

**Comment by saramsey** [comment]
Ran this test on `buildkg2.rtx.ai`:
```
bash -x /home/ubuntu/kg2-code/extract-kegg.sh /home/ubuntu/kg2-build/kegg.json > /home/ubuntu/kg2-build/extract-kegg.log 2>&1
```
and got this error:
```
+ /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/query_kegg.py /home/ubuntu/kg2-build/kegg.json
Traceback (most recent call last):
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/cachecontrol/caches/file_cache.py", line 72, in __init__
    from lockfile import LockFile
ModuleNotFoundError: No module named 'lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/query_kegg.py", line 124, in <module>
    kg2_util.save_json(run_queries(), args.outputFile, True)
  File "/home/ubuntu/kg2-code/query_kegg.py", line 90, in run_queries
    for results in send_query(query).split('\n'):
  File "/home/ubuntu/kg2-code/query_kegg.py", line 37, in send_query
    requests = CacheControlHelper()
  File "/home/ubuntu/RTX-KG2/cache_control_helper.py", line 32, in __init__
    self.sess = CacheControl(requests.session(), heuristic=CustomHeuristic(days=30), cache=FileCache('.web_cache'))
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/cachecontrol/caches/file_cache.py", line 82, in __init__
    raise ImportError(notice)
ImportError:
NOTE: In order to use the FileCache you must have
lockfile installed. You can install it via pip:
  pip install lockfile
```
