### ISSUE TITLE
KeyError in ensembl_json_to_kg_json.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#111]
Found in the file `~/kg2-build/build-kg2-snakemake.log` on `buildkg2.rtx.ai`:
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/ensembl_json_to_kg_json.py", line 180, in <module>
    graph = make_kg2_graph(input_file_name, test_mode)
  File "/home/ubuntu/kg2-code/ensembl_json_to_kg_json.py", line 137, in make_kg2_graph
    name = transcript['name']
KeyError: 'name'
```
(see #104 for parent issue)

**Comment by saramsey** [comment]
tentatively marking this as a bug

**Comment by saramsey** [comment]
OK, commit 95a14d8 should fix this, I hope
