### ISSUE TITLE
AssertionError in multi_ont_to_json_kg.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#113]
This error message was found in the logfile `build-multi-ont-kg.log` during the build for KG2.7.2 on `buildkg2.rtx.ai` (see #104 for parent issue for the build):
```
[http://purl.obolibrary.org/obo/pr.owl] object node ontology ID has no curie ID in the map: https://bar.utoronto.ca/thalemine/portal.do?externalids=AT5G13700
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1361, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 190, in make_kg2
    map_of_node_ontology_ids_to_curie_ids)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1098, in get_rels_dict
    assert predicate_label is not None
AssertionError
```

**Comment by saramsey** [comment]
Here is the complete `build-multi-ont-kg.log` file on `buildkg2.rtx.ai`, containing the aforementioned error message:
[build-multi-ont-kg.log.zip](https://github.com/RTXteam/RTX-KG2/files/6947653/build-multi-ont-kg.log.zip)

**Comment by saramsey** [comment]
Note: Line numbers in this error message refer to the version of `multi_ont_to_json_kg.py` that is in the `issue95` branch

**Comment by saramsey** [comment]
Here's hoping 18a4f30 fixes the issue....😬
