### ISSUE TITLE
TypeError in kg_json_to_tsv.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#117]
In the logfile `~/kg2-build/build-kg2-snakemake.log` on `buildkg2.rtx.ai`, the following error occurred:
```
ESC[33mJob counts:
        count   jobs
        1       TSV
        1ESC[0m
Start time:  2021-08-09 21:58:54
Start load:  2021-08-09 21:58:54
End load:  2021-08-09 22:25:26
Start nodes:  2021-08-09 22:25:26
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/kg_json_to_tsv.py", line 318, in <module>
    nodes(graph, output_file_location)
  File "/home/ubuntu/kg2-code/kg_json_to_tsv.py", line 187, in nodes
    value = value.replace('\t', ' ').replace('\n', ' ').replace('\r', ' ')
AttributeError: 'NoneType' object has no attribute 'replace'
ESC[32m[Mon Aug  9 22:33:49 2021]ESC[0m
ESC[31mError in rule TSV:ESC[0m
ESC[31m    jobid: 0ESC[0m
ESC[31m    output: /home/ubuntu/kg2-build/tsv_placeholder.emptyESC[0m
ESC[31mESC[0m
ESC[31mRuleException:
CalledProcessError in line 74 of /home/ubuntu/kg2-code/Snakefile-post-etl:
Command 'set -euo pipefail;  /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/kg_json_to_tsv.py /home/ubuntu/kg2-build/kg2-simplified.json /home/ubuntu/kg2-build/TSV' returned non-zero exit status 1.
  File "/home/ubuntu/kg2-code/Snakefile-post-etl", line 74, in __rule_TSV
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in runESC[0m
ESC[31mExiting because a job execution failed. Look above for error messageESC[0m
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ubuntu/.snakemake/log/2021-08-09T171845.595471.snakemake.log
```
complete logfile here:
[build-kg2-snakemake.log.zip](https://github.com/RTXteam/RTX-KG2/files/6957769/build-kg2-snakemake.log.zip)

**Comment by saramsey** [comment]
Parent issue for the KG2.7.2 build is #104

**Comment by saramsey** [comment]
OK, hopefully 9efe062 fixes the issue.

**Comment by saramsey** [comment]
I decided I didn't like 9efe062; replaced with 4c1311c

**Comment by saramsey** [comment]
build now being resumed (see #104 for updates)
