### ISSUE TITLE
ModuleNotFoundError in setup-kg2-neo4j.sh

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#119]
Running the setup script `setup-kg2-neo4j.sh` on instance `kg2endpoint4.rtx.ai`, getting the following `ModuleNotFoundError`:
```
Collecting pandas (from ontobio==1.10.1->-r /home/ubuntu/kg2-code/requirements-kg2-neo4j.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/12/01/360d7f444f910ae16496c07e3f003cb8c641b4ca6c033408a4469a904df3/pandas-1.3.1.tar.gz (4.7MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gtghlz5t/pandas/setup.py", line 18, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gtghlz5t/pandas/
```

**Comment by saramsey** [comment]
For to add, we are running the setup script to configure the `kg2endpoint4.rtx.ai` instance to host the Neo4j database for KG2.7.2. See parent issue #104 for operations tracking for that work.
