### ISSUE TITLE
KG2.7.3 build

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#138]
Aiming to do a build KG2.7.3 the week of Aug. 30 - Sep. 3, to get the fix for #131 out as soon as possible.

**Comment by saramsey** [comment]
Hi @acevedol: we might want to hold off a bit to see if we can also get the fix for #141 in the 2.7.3 build, let's discuss

**Comment by saramsey** [comment]
Hi @acevedol just an FYI, I have committed what I hope is a fix for #141 in the `issue-141` branch. I am doing some more thorough testing now. If everything looks good, I will push that commit upstream to the `master` branch.

**Comment by saramsey** [comment]
OK, I have pushed the fix for #141 to the `master` branch. I think it is ready for inclusion in the KG2.7.3 build.

**Comment by acevedol** [comment]
deleted kg2-code on buildkg2.rtx.ai and cloned it from the repo.

**Comment by acevedol** [comment]
Ran a dry run with `bash -x ~/kg2-code/build-kg2-snakemake.sh all -F -n`
The log file shows all 48 jobs, as expected.

**Comment by acevedol** [comment]
Running full build with `bash -x ~/kg2-code/build-kg2-snakemake.sh all -F`

**Comment by acevedol** [comment]
Build crashed at DrugCentral rule 
<img width="807" alt="Screen Shot 2021-09-02 at 8 39 24 AM" src="https://user-images.githubusercontent.com/59181061/131874452-4a3a849f-5d47-4675-83bf-3a047cabed69.png">

**Comment by acevedol** [comment]
Error in extract-drugcentral.log is `Error: role "jjyang" does not exist`

**Comment by acevedol** [comment]
I'm not sure if this is an actual problem yet, but checking kg2-build/build-kg2-snakemake.log shows an error with Rule Unichem, but the script is still running
<img width="946" alt="Screen Shot 2021-09-07 at 4 14 34 PM" src="https://user-images.githubusercontent.com/59181061/132422110-b8902c9a-17b7-4925-9954-a6559dee856d.png">

**Comment by acevedol** [comment]
Changes to extract-drugcentral and a little bit of command line correcting finished extract-drugcentral correctly. Error for jhang came from the role being created out of order

**Comment by acevedol** [comment]
Another error 
<img width="805" alt="Screen Shot 2021-09-08 at 8 13 08 PM" src="https://user-images.githubusercontent.com/59181061/132616384-49bc103b-5487-44b5-a51b-da9edc463e64.png">
Presumably due to the UniChem error since the drug central script was able to complete successfully

**Comment by acevedol** [comment]
Unichem error using curl -v 
<img width="808" alt="Screen Shot 2021-09-09 at 10 45 29 AM" src="https://user-images.githubusercontent.com/59181061/132736430-eb11e42b-777a-4fa1-abf7-0430e6881bc5.png">

**Comment by acevedol** [comment]
UniChem seems to be an access control problem. The script uses an anonymous user and is denied access. I'm digging in https://www.ebi.ac.uk for possible solutions.

**Comment by acevedol** [comment]
UDRI version 385 appears to be current. 375 no longer available
<img width="777" alt="Screen Shot 2021-09-09 at 1 24 12 PM" src="https://user-images.githubusercontent.com/59181061/132757519-4261a706-4dd1-4538-b8fb-15a0cd55504d.png">

**Comment by acevedol** [comment]
Error in build-multi-ont-kg.log
<img width="1006" alt="Screen Shot 2021-09-09 at 2 42 16 PM" src="https://user-images.githubusercontent.com/59181061/132766592-b436daff-65ed-4d8d-8a27-3925a19e02d9.png">
<img width="1008" alt="Screen Shot 2021-09-09 at 2 42 58 PM" src="https://user-images.githubusercontent.com/59181061/132766598-b36afabc-4a82-4af1-b5ac-d758a2fe324f.png">

**Comment by acevedol** [comment]
I am still stuck on the above error. The line `/usr/bin/java -Xms2G -Xmx255683G -DentityExpansionLimit=4086000 -Djava.awt.headless=true -classpath /home/ubuntu/kg2-build/owltools owltools.cli.CommandLineInterface biolink-model.owl.ttl -o -f json /tmp/kg2-97rgzijn.json` seems to be where it's stuck, but I can't find where to change the settings for the VM stack size

**Comment by saramsey** [comment]
OK, this indicates a bug:
```
/usr/bin/java -Xms2G -Xmx255683G
```
since 255683G is 255 Terabytes (!). I am checking on the cause of this bug now...

**Comment by saramsey** [comment]
I suspect my code changes to `get-system-memory.sh` for #137 caused this bug. Testing that hunch now...

**Comment by saramsey** [comment]
Commit 40d9a6a should fix the problem with `build-multi-ont-kg.log`

**Comment by acevedol** [comment]
Another error in Ontologies rule 
<img width="925" alt="Screen Shot 2021-09-14 at 7 02 28 PM" src="https://user-images.githubusercontent.com/59181061/133358352-035b5291-2cca-416e-8a75-aea4fc807ec8.png">

**Comment by acevedol** [comment]
The fix above for get-system-memory.sh did correct the problem. Thank you, Steve!

**Comment by acevedol** [comment]
Ontology exited with error 
`Reading ontology file: foodon.owl; size: 6944.69 KiB
/usr/bin/java -Xms2G -Xmx249G -DentityExpansionLimit=4086000 -Djava.awt.headless=true -classpath /home/ubuntu/kg2-build/owltools owltools.cli.CommandLineInterface foodon.owl -o -f json /tmp/kg2-_afrl46i.json
2021-09-15 02:38:43,998 ERROR (CommandRunner:4815) could not parse:foodon.owl
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/foodon/imports/dietary_supplement_import.owl> Cause: https://raw.githubusercontent.com/FoodOntology/foodon/master/imports/dietary_supplement_import.owl
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1870)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1537)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:194)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1545)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.statementWithResourceValue(RDFParser.java:370)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.EmptyPropertyElement.startElement(StartRDF.java:236)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.PropertyElementList.startElement(StartRDF.java:658)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:201)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:145)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:73)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1254)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1208)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1108)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1064)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:163)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:150)
	at owltools.io.ParserWrapper.parse(ParserWrapper.java:132)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4803)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: https://raw.githubusercontent.com/FoodOntology/foodon/master/imports/dietary_supplement_import.owl
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:230)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1254)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1208)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1108)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1825)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1863)
	... 33 more
Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/FoodOntology/foodon/master/imports/dietary_supplement_import.owl
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:179)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:141)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:264)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	... 38 more
Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/FoodOntology/foodon/master/imports/dietary_supplement_import.owl
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3099)
	at java.base/java.net.URLConnection.getContentEncoding(URLConnection.java:530)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:406)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:136)
	... 41 more
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1362, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 143, in make_kg2
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 67, in load_ont_file_return_ontology_and_metadata
    ontology = kg2_util.make_ontology_from_local_file(file_name, save_pickle=save_pickle)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 783, in make_ontology_from_local_file
    check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['owltools', 'foodon.owl', '-o', '-f', 'json', '/tmp/kg2-_afrl46i.json']' returned non-zero exit status 1.`

**Comment by acevedol** [comment]
Error in Rule Simplify 
```
relation curie is missing from the YAML config file: RO:0002470
There are relation curies missing from the yaml config file. Please add them and try again. Exiting.
```

**Comment by acevedol** [comment]
KG2 build completed. The complete log is at /home/ubuntu/.snakemake/log/2021-09-16T181654.939719.snakemake.log

**Comment by acevedol** [comment]
On build instance, kg2-version.txt shows `2.7.3` and tagged repo with KG2.7.3

**Comment by acevedol** [comment]
kg2-simplified-report.json grew from 48KB to 50 KB 
4308 more edges
1525 more nodes

**Comment by acevedol** [comment]
I accidentally deleted the checklist at the top of this

**Comment by acevedol** [comment]
- [ ] make sure issue95 branch Travis CI test-suite passes
- [ ]   create a r5a.8xlarge instance kg2build.rtx.ai for the build
- [ ]   clone the RTX-KG2 repo into the instance but use the issue95 branch
- [ ]   update the README.md in the issue95 branch to reflect the new flags added for Snakemake
- [ ]   download TSV file for the infores Google Sheet and copy it into the instance
- [ ]   run the infores verification script on the TSV file in the instance
- [ ]   run a "all -F" build with the "-n" flag
- [ ]   check the output of the "-n" run to make sure every target will be run
- [ ]   run a "all -F" build without the "-n" flag (this should take approximately 48 hours)
- [ ]   verify that the new build is in fact versioned 2.7.3
- [ ]   check report file kg2-simplified-report.json; compare against previous kg2-simplified-report.json to identify any major changes
- [ ]   install the new KG2 TSV files into Neo4j on kg2endpoint4.rtx.ai
- [ ]   create a DNS CNAME record for kg2-7-2.rtx.ai pointing to kg2endpoint4.rtx.ai
- [ ]   document the build in kg2-versions.md in the issue95 branch
- [ ]   tag the RTX-KG2 master branch and do a GitHub "release" with version KG2.7.3
- [ ]   build Node Synonymizer against KG2.7.3-neo4j
- [ ]   build KG2.7.3c
- [ ]   validate KG2.7.3c
- [ ]   push kg2-simplified.json.gz to NCATS repo #130
- [ ]   push kg2c_lite_2.7.3.json.gz to NCATS repo
- [ ]   coordinate with Amy
- [ ]   coordinate with Eric, Finn, and Chunyu for handof

**Comment by acevedol** [comment]
Installed new tsv files on kg2enpoint4.rtx.ai.
The log file `kg2-build/setup-kg2-neo4j.log` ends with `======= script finished ======`

**Comment by acevedol** [comment]
Updated CNAME for kg2endpoint4.rtx.ai to point to kg2endpoint-kg2-7-3.rtx.ai

**Comment by acevedol** [comment]
Made directory on rtxconfig@arax.ncats.io for KG2.7.3

**Comment by acevedol** [comment]
updated kg2c_config.json 
<img width="635" alt="Screen Shot 2021-09-17 at 10 12 39 PM" src="https://user-images.githubusercontent.com/59181061/133873527-9273dc35-0bb6-4c5f-8bc4-e425d6b780dd.png">

**Comment by acevedol** [comment]
Error running synonymizer. Appears similar to an error from the last build
<img width="1265" alt="Screen Shot 2021-09-17 at 10 20 21 PM" src="https://user-images.githubusercontent.com/59181061/133873732-7af14bab-e1da-4208-ac3e-6a085394faca.png">

**Comment by amykglen** [comment]
ok, fix is pushed to the `kg2integration` branch (in the RTX repo). (was related to Finn's changes to `configv2.json` yesterday -- made some tweaks so the KG2c build shouldn't be so fragile in terms of config files anymore in https://github.com/RTXteam/RTX/commit/2509ca4314d67a1e5185ba2bcc18b02c0cc27fad)

also worth noting that this KG2c build should be done from the `kg2integration` branch - probably should add a step to the build checklist to touch base about which branch the KG2c build should be done from. :)

**Comment by acevedol** [comment]
Added "Check with Amy which branch to use for building kg2c" to checklist

**Comment by acevedol** [comment]
NodeSynonymizer build finished with `2021-09-18 20:43:23,810 INFO: Done building synonymizer.`

**Comment by acevedol** [comment]
Checked arax.ncats.io to make sure synonymizer files are presen
<img width="686" alt="Screen Shot 2021-09-18 at 1 50 35 PM" src="https://user-images.githubusercontent.com/59181061/133908384-2943127a-75cd-4635-ae17-f0ad4f77b138.png">
t

**Comment by acevedol** [comment]
Updated kg2c_config.json to build kg2c
<img width="674" alt="Screen Shot 2021-09-18 at 1 48 40 PM" src="https://user-images.githubusercontent.com/59181061/133908416-200f8a42-c03a-4aeb-aa35-55e6052562dd.png">

**Comment by acevedol** [comment]
BuildKG2C completed and the files on arax.ncats.io are slightly larger than in KG2.7.2C
<img width="1092" alt="Screen Shot 2021-09-19 at 9 13 29 AM" src="https://user-images.githubusercontent.com/59181061/133934759-15959a71-f3cf-44c5-8e99-029f0945af73.png">

**Comment by acevedol** [comment]
Loading kg2c into Neo4J on kg2canonicalized.rtx.ai with `bash -x RTX/code/kg2c/tsv-to-neo4j-canonicalized.sh`

**Comment by acevedol** [comment]
Neo4J loading completed with 
```
Mon Sep 20 17:46:33 UTC 2021
+ echo '================ script finished ============================'
================ script finished ============================
```

**Comment by acevedol** [comment]
Updated CName for kg2canonicalized.rtx.ai
<img width="657" alt="Screen Shot 2021-09-20 at 10 48 44 AM" src="https://user-images.githubusercontent.com/59181061/134050022-3b4c36b9-e92d-419b-a9aa-0af9dd3d755a.png">

**Comment by acevedol** [comment]
Validated results at http://kg2-7-3c.rtx.ai:7474/browser/ and results make sense

**Comment by acevedol** [comment]
This was finished a while back
