### ISSUE TITLE
issue with foodon.owl include

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#150]
This issue brought to my attention by @acevedol who first logged it in #138 

```
Reading ontology file: foodon.owl; size: 6944.69 KiB /usr/bin/java -Xms2G -Xmx249G -DentityExpansionLimit=4086000 -Djava.awt.headless=true -classpath /home/ubuntu/kg2-build/owltools 
owltools.cli.CommandLineInterface foodon.owl -o -f json /tmp/kg2-_afrl46i.json 2021-09-15 02:38:43,998 ERROR (CommandRunner:4815) could not parse:foodon.owl 
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: http://purl.obolibrary.org/obo/foodon/imports/dietary_supplement_import.owl Cause: https://raw.githubusercontent.com/FoodOntology/foodon/master/imports/dietary_supplement_import.owl at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeL… S
```

**Comment by saramsey** [comment]
In `kg2-build` on `buildkg2.rtx.ai`, ran this:
```
owltools foodon.owl -o -f json test.json
```
and got this error:
```
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/foodon/imports/dietary_supplement_import.owl> Cause: https://raw.githubusercontent.com/FoodOntology/foodon/master/imports/dietary_supplement_import.owl
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1870)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1537)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:194)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1545)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.statementWithResourceValue(RDFParser.java:370)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.EmptyPropertyElement.startElement(StartRDF.java:236)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.PropertyElementList.startElement(StartRDF.java:658)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:201)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:145)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:73)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1254)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1208)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1108)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1064)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:163)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:150)
	at owltools.io.ParserWrapper.parse(ParserWrapper.java:132)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4803)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: https://raw.githubusercontent.com/FoodOntology/foodon/master/imports/dietary_supplement_import.owl
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:230)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1254)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1208)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1108)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1825)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1863)
	... 33 more
Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/FoodOntology/foodon/master/imports/dietary_supplement_import.owl
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:179)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:141)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:264)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	... 38 more
Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/FoodOntology/foodon/master/imports/dietary_supplement_import.owl
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3099)
	at java.base/java.net.URLConnection.getContentEncoding(URLConnection.java:530)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:406)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:136)
	... 41 more
```

**Comment by saramsey** [comment]
Removed the line 
```
<         <owl:imports rdf:resource="&obo;foodon/imports/dietary_supplement_import.owl"/>
```
from `foodon.owl` and saved it as `foodon-issue150.owl`.

**Comment by saramsey** [comment]
It now works:
```
owltools foodon-issue150.owl -o -f json test.json
```
Doing a modification of `ont-load-inventory.yaml` in-place on the build system

**Comment by saramsey** [comment]
<img width="978" alt="Screen Shot 2021-09-15 at 10 41 23 AM" src="https://user-images.githubusercontent.com/5562107/133482787-356f1ac1-f88c-4ab5-8204-74cbf2d94074.png">

**Comment by saramsey** [comment]
The local code and ontology file patches on `buildkg2.rtx.ai` should hopefully fix the build KG2.7.3. We need to report the issue with the failing OWL include in `foodon.owl` 
```
<owl:imports rdf:resource="&obo;foodon/imports/dietary_supplement_import.owl"/>
```
to the [Food Ontology project](https://github.com/FoodOntology/foodon) via their [Issue Tracker](https://github.com/FoodOntology/foodon/issues). @acevedol can you please notify them of the issue?  Thanks.

**Comment by saramsey** [comment]
I don't think there are any permanent code changes warranted by this issue, under the presumption that the issue in `foodon.owl` will be fixed in short order and then will not affect future KG2 builds.

**Comment by ddooley** [comment]
This is now fixed in foodon.owl. - thanks for reporting it and sorry for hiccup.  It cropped up about 4 days ago after a file name change that wasn't fully implemented.  Try loading it again.

(In future we'll have a single-file version of foodon that will be bigger but won't run the risk of file import name change bugs like the one you encountered.)

**Comment by saramsey** [comment]
Thanks, @ddooley. Would be great to have the option of a monolithic OWL file for `foodon`.

**Comment by ddooley** [comment]
Just a little news that now the root github foodon.owl is "monolithic" - it has all imports rolled up into it.
