### ISSUE TITLE
UnboundLocalError in multi_ont_to_json_kg.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#173]
In running some tests on `multi_ont_to_json_kg.py`, I tripped the following error:
```
Traceback (most recent call last):
  File "multi_ont_to_json_kg.py", line 1362, in <module>
    save_pickle)
  File "multi_ont_to_json_kg.py", line 190, in make_kg2
    map_of_node_ontology_ids_to_curie_ids)
  File "multi_ont_to_json_kg.py", line 1066, in get_rels_dict
    predicate_iri = curie_to_uri_expander(predicate_curie)
UnboundLocalError: local variable 'predicate_curie' referenced before assignment
```

**Comment by saramsey** [comment]
Commit 09964eb should fix it

**Comment by saramsey** [comment]
Hi @acevedol you may want to `git cherry-pick` commit 09964eb into the branch where you are doing the biolink work for the KG2.7.4 build
