### ISSUE TITLE
AssertionError in multi_ont_to_json_kg.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#174]
In doing some testing of `multi_ont_to_json_kg.py`, I triggered an error:
```
Traceback (most recent call last):
  File "multi_ont_to_json_kg.py", line 1363, in <module>
    save_pickle)
  File "multi_ont_to_json_kg.py", line 190, in make_kg2
    map_of_node_ontology_ids_to_curie_ids)
  File "multi_ont_to_json_kg.py", line 1048, in get_rels_dict
    assert False, "Cannot map predicate name: " + edge_pred_string + " to a predicate CURIE, in ontology: " + ontology.id
AssertionError: Cannot map predicate name: inverseOf to a predicate CURIE, in ontology: https://w3id.org/biolink/biolink-model
```

**Comment by saramsey** [comment]
commit `a238609` should fix the issue
