### ISSUE TITLE
Compliance with biolink model 2.2.11

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#187]
Updating to biolink model 2.2.11. Many mappings changed
- [x] Get up to date with biolink model 2.2.11
- [x] run a test build

**Comment by acevedol** [comment]
Created branch issue-187 for work on updating kg2pre

**Comment by acevedol** [comment]
As of 12/16/2021 the biolink model's latest version is 2.2.12

**Comment by acevedol** [comment]
Note there is a deprecation warning
```
  DeprecationWarning,
/home/ubuntu/kg2-venv/lib/python3.7/site-packages/rdflib_jsonld/__init_
_.py:12: DeprecationWarning: The rdflib-jsonld package has been integra
ted into rdflib as of rdflib==6.0.1.  Please remove rdflib-jsonld from
your project's dependencies.
```

**Comment by acevedol** [comment]
In test build, error in rule Ontologies_and_TTL

```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1364, in <
module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 143, in ma
ke_kg2
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 67, in loa
d_ont_file_return_ontology_and_metadata
    ontology = kg2_util.make_ontology_from_local_file(file_name, save_p
ickle=save_pickle)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 801, in make_ontology_f
rom_local_file
    ont_return = load_ontology_from_owl_or_json_file(json_file)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 762, in load_ontology_f
rom_owl_or_json_file
ke_kg2
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 67, in loa
d_ont_file_return_ontology_and_metadata
    ontology = kg2_util.make_ontology_from_local_file(file_name, save_p
ickle=save_pickle)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 801, in make_ontology_f
rom_local_file
    ont_return = load_ontology_from_owl_or_json_file(json_file)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 762, in load_ontology_f
rom_owl_or_json_file
    return ont_factory.create(ontology_file_name, ignore_cache=True)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/ontobio/ontol
_factory.py", line 76, in create
    return create_ontology(handle, **args)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/cachier/core.
py", line 129, in func_wrapper
    return func(*args, **kwds)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/ontobio/ontol
_factory.py", line 93, in create_ontology
    ont = translate_file_to_ontology(handle, **args)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/ontobio/ontol
_factory.py", line 155, in translate_file_to_ontology
    g = obograph_util.convert_json_file(handle, **args)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/ontobio/obogr
aph_util.py", line 116, in convert_json_file
    return convert_json_object(json.loads(jsonstr), **args)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/ontobio/obogr
aph_util.py", line 137, in convert_json_object
    property_chain_axioms=property_chain_axioms, **args)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/ontobio/obogr
aph_util.py", line 45, in add_obograph_digraph
    digraph.node[id]['label'] = n['lbl']
AttributeError: 'MultiDiGraph' object has no attribute 'node'
```

**Comment by acevedol** [comment]
Error in Rule Ontologies and TTL
```
Reading ontology JSON file: umls-mth.json; size: 291092.37 KiB
file: umls-mth.ttl; last modified: 2021-10-28 07:49:13 GMT
Calling get_inverse_rels
Calling make_nodes_dict_from_ontologies_list
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1364, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 177, in make_kg2
    select_datatype_properties) # temporary addition for Ontobio Issue #507
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 526, in make_nodes_dict_from_ontologies_list
    [biolink_category_tree, mappings_to_categories] = generate_biolink_category_tree(first_ontology, curies_to_categories)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 385, in generate_biolink_category_tree
    biolink_category_tree = kg2_util.get_biolink_category_tree(biolink_ontology)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 422, in get_biolink_category_tree
    parent = biolink_ontology.node(parent)['lbl']
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/ontobio/ontol.py", line 341, in node
    return self.get_graph().node[id]
AttributeError: 'MultiDiGraph' object has no attribute 'node'
```

**Comment by acevedol** [comment]
I keep running into the error `AttributeError: 'MultiDiGraph' object has no attribute 'node'`. The `MultiDiGraph` object looks like it comes from `networkx`. The `node` attribute should be `nodes` in networkx version 2.6.2. 

@saramsey This seems somewhat related to https://github.com/RTXteam/RTX-KG2/issues/28.

**Comment by acevedol** [comment]
ontobio requires networkx version 2.3 at minimum now. I updated the networkx version in requirements-kg2-build.txt

**Comment by acevedol** [comment]
Updating networkx to 2.3 seems to have fixed the Attribute Error

Now there's a Value Error
```
warning:  for key: knowledge_source, dropping second value: OBO:ro.owl; keeping first value: OBO:go/extensions/go-plus.owl
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1364, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 177, in make_kg2
    select_datatype_properties) # temporary addition for Ontobio Issue #507
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 715, in make_nodes_dict_from_ontologies_list
    bpv_pred_curie = convert_bpv_pred_to_curie_func(bpv_pred)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1321, in <lambda>
    curie_expander)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1312, in convert_bpv_predicate_to_curie
    raise ValueError('unable to expand CURIE: ' + bpv_pred)
ValueError: unable to expand CURIE: dcterms:description
```

**Comment by acevedol** [comment]
Error on Rule Finish:
```
RuleException:
NameError in line 15 of /home/ubuntu/kg2-code/Snakefile:
The name 'simplified_output_nodes_file_full' is unknown in this context. Please make sure that you defined that variable. Also note that braces not used for variable access have to be escaped by repeating them, i.e. {{print $1}}
  File "/home/ubuntu/kg2-code/Snakefile", line 15, in __rule_Finish
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by saramsey** [comment]
>  I keep running into the error AttributeError: 'MultiDiGraph' object has no attribute 'node'. The MultiDiGraph object looks like it comes from networkx. The node attribute should be nodes in networkx version 2.6.2.

I wonder if we have a new version of `networkx` installed or something?  Can I see a stack trace?
