### ISSUE TITLE
Uniprot Conversion Unbound Local Error

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#203]
Error in test build of KG2
```
[Fri May  6 19:09:06 2022]
Error in rule UniProtKB_Conversion:
    jobid: 8
    output: /home/ubuntu/kg2-build/kg2-uniprotkb.json
    log: /home/ubuntu/kg2-build/uniprotkb-dat-to-json.log (check log file(s) for error message)
    shell:
        /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/uniprotkb_dat_to_json.py  /home/ubuntu/kg2-build/uniprotkb/uniprot_sprot.dat /home/ubuntu/kg2-build/kg2-uniprotkb.json > /home/ubuntu/kg2-build/uniprotkb-dat-to-json.log 2>&1
        (exited with non-zero exit code)
```

More info in log: 
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/uniprotkb_dat_to_json.py", line 353, in <module>
    test_mode)
  File "/home/ubuntu/kg2-code/uniprotkb_dat_to_json.py", line 122, in parse_records_from_uniprot_dat
    return [record_list, update_date, version]
UnboundLocalError: local variable 'update_date' referenced before assignment
```

_Originally posted by @acevedol in https://github.com/RTXteam/RTX-KG2/issues/202#issuecomment-1119936583_

**Comment by acevedol** [comment]
It looks like the uniprot data is missing, so I am going to add the uniprot extraction rule to the run

**Comment by acevedol** [comment]
The contents of `uniprot_sprot.dat` were moved to another file for testing. I moved it back and the error should resolve.

**Comment by acevedol** [comment]
Rule completed successfully.
