### ISSUE TITLE
Error in Rule HMDB_Conversion

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#204]
Another error: 
```
[Fri May  6 19:09:05 2022]
Error in rule HMDB_Conversion:
    jobid: 18
    output: /home/ubuntu/kg2-build/kg2-hmdb.json
    log: /home/ubuntu/kg2-build/hmdb-xml-to-kg-json.log (check log file(s) for error m
essage)
    shell:
        /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/hmdb_xml_to_kg_json
.py  /home/ubuntu/kg2-build/hmdb_metabolites.xml /home/ubuntu/kg2-build/kg2-hmdb.json
> /home/ubuntu/kg2-build/hmdb-xml-to-kg-json.log 2>&1
```
With additional info
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/hmdb_xml_to_kg_json.py", line 625, in <module>
    metabolite_data = xmltodict.parse(xml_file.read())
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

_Originally posted by @acevedol in https://github.com/RTXteam/RTX-KG2/issues/202#issuecomment-1120017365_

**Comment by acevedol** [comment]
The file `hmdb_metabolites.xml` was moved to another name for testing. I renamed the file and this error should be fixed.

**Comment by acevedol** [comment]
Re-ran rule `HMDB_Conversion` and it completed successfully
