### ISSUE TITLE
Error in `Rule ValidationTests`

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#229]
Error in `Rule ValidationTests`
```
[Mon Aug 15 16:58:42 2022]
Error in rule ValidationTests:
    jobid: 28
    output: /home/ubuntu/kg2-build/validation-placeholder.empty
    log: /home/ubuntu/kg2-build/run-validation-tests.log (check log file(s) for error message)
    shell:
        bash -x /home/ubuntu/kg2-code/run-validation-tests.sh > /home/ubuntu/kg2-build/run-validation-tests.l
og 2>&1 && touch /home/ubuntu/kg2-build/validation-placeholder.empty
        (exited with non-zero exit code)
```

_Originally posted by @acevedol in https://github.com/RTXteam/RTX-KG2/issues/226#issuecomment-1215734532_

**Comment by acevedol** [comment]
```
+ /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/validate_curies_to_categories_yaml.py /home/ubuntu/kg2-code/curies-to-categories.yaml /home/ubuntu/kg2-code/curies-to-urls-map.yaml https://raw.githubusercontent.com/biolink/biolink-model/3.0.0/biolink-model.owl.ttl /home/ubuntu/kg2-build/biolink-model.owl.ttl
/home/ubuntu/kg2-venv/lib/python3.7/site-packages/rdflib_jsonld/__init__.py:12: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  DeprecationWarning,
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/validate_curies_to_categories_yaml.py", line 39, in <module>
    kg2_util.download_file_if_not_exist_locally(biolink_model_url, biolink_model_file_name)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 625, in download_file_if_not_exist_locally
    with urllib.request.urlopen(url, context=ctx) as u, open(temp_file_name, 'wb') as f:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in openresponse = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by acevedol** [comment]
The current biolink version number includes a "v" before the number `v3.0.0`, which caused the error in the validation script.

**Comment by acevedol** [comment]
New error on same rule
```
+ /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/validate_curies_to_urls_map_yaml.py /home/ubuntu/kg2-code/curies-to-urls-map.yaml https://raw.githubusercontent.com/biolink/biolink-model/v3.0.0/context.jsonld
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/validate_curies_to_urls_map_yaml.py", line 64, in <module>
    map_data_bidir = make_map_from_list(map_data_bidir_list, reverse=False)
  File "/home/ubuntu/kg2-code/validate_curies_to_urls_map_yaml.py", line 44, in make_map_from_list
    assert subkey not in ret_map, subkey
AssertionError: NCBITaxon
```

**Comment by acevedol** [comment]
New error
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/validate_predicate_remap_yaml.py", line 160, in <module>
    assert subinfo[1] not in inverted_relations, (relation, subinfo[1], {'Inverted Relations': inverted_relations})
AssertionError: ('CHEMBL.MECHANISM:modulator', 'biolink:entity_regulates_entity', {'Inverted Relations': ['biolink:superclass_of', 'biolink:superclass_of', 'biolink:narrow_match', 'biolink:affects_response_to', 'biolink:entity_regulates_entity', 'biolink:entity_regulates_entity', 'biolink:gene_product_of', 'biolink:has_gene_product', 'biolink:has_gene_product', 'biolink:has_gene_product', 'biolink:transcribed_to', 'biolink:translation_of', 'biolink:condition_associated_with_gene', 'biolink:caused_by', 'biolink:caused_by', 'biolink:treated_by', 'biolink:treated_by', 'biolink:has_biomarker', 'biolink:expresses', 'biolink:location_of', 'biolink:location_of', 'biolink:part_of', 'biolink:part_of', 'biolink:part_of', 'biolink:participates_in', 'biolink:participates_in', 'biolink:actively_involves', 'biolink:enables', 'biolink:enabled_by', 'biolink:derives_into', 'biolink:derives_from', 'biolink:derives_from', 'biolink:is_metabolite_of', 'biolink:produced_by', 'biolink:preceded_by', 'biolink:preceded_by', 'biolink:preceded_by']})
```

**Comment by acevedol** [comment]
Error
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/validate_predicate_remap_yaml.py", line 147, in <module>
    assert core_predicate not in biolink_to_external_mappings, (relation, core_predicate)
AssertionError: ('BFO:0000050', 'biolink:has_part')
```

**Comment by acevedol** [comment]
Error
```
Reading ontology JSON file: /home/ubuntu/kg2-build/biolink-model.owl.json; size: 936.70 KiB
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/validate_kg2_util_curies_urls_categories.py", line 57, in <module>
    assert curie is not None, url_str
AssertionError: https://www.dgidb.org/
```

**Comment by acevedol** [comment]
Validation rules passed
