### ISSUE TITLE
Error with NCBI Gene Conversion

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#233]
Error with NCBI Gene Conversion
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/drugcentral_json_to_kg_json.py", line 277, in <module>
    json_data = json.load(input_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/ncbigene_tsv_to_kg_json.py", line 183, in <module>
    graph = make_kg2_graph(input_file_name, test_mode)
  File "/home/ubuntu/kg2-code/ncbigene_tsv_to_kg_json.py", line 149, in make_kg2_graph
    modify_date)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 762, in make_edge_biolink
    update_date)
TypeError: make_edge() missing 2 required positional arguments: 'qualified_object_direction' and 'knowledge_source'
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/intact_tsv_to_kg_json.py", line 147, in <module>
    edge = make_edge(row)
  File "/home/ubuntu/kg2-code/intact_tsv_to_kg_json.py", line 134, in make_edge
    update_date)
TypeError: make_edge() missing 2 required positional arguments: 'qualified_object_direction' and 'knowledge_source'
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/unichem_tsv_to_edges_json.py", line 68, in <module>
    edges.append(make_xref(subject_curie_id, object_curie_id, update_date))
  File "/home/ubuntu/kg2-code/unichem_tsv_to_edges_json.py", line 34, in make_xref
    update_date)
TypeError: make_edge() missing 2 required positional arguments: 'qualified_object_direction' and
'knowledge_source'
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/repodb_csv_to_kg_json.py", line 75, in <module>
    graph = make_kg2_graph(input_file_name, test_mode)
  File "/home/ubuntu/kg2-code/repodb_csv_to_kg_json.py", line 61, in make_kg2_graph
    update_date=None)
TypeError: make_edge() missing 3 required positional arguments: 'qualified_predicate', 'qualified
_object_aspect', and 'qualified_object_direction'
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/disgenet_tsv_to_kg_json.py", line 94, in <module>
    edges = make_edges(input_file, args.test)
  File "/home/ubuntu/kg2-code/disgenet_tsv_to_kg_json.py", line 83, in make_edges
    update_date)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 762, in make_edge_biolink
    update_date)
TypeError: make_edge() missing 2 required positional arguments: 'qualified_object_direction' and
'knowledge_source'
[Tue Sep  6 15:25:30 2022]
Error in rule DrugCentral_Conversion:
    jobid: 23
    output: /home/ubuntu/kg2-build/kg2-drugcentral.json
    shell:
        /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/drugcentral_json_to_kg_json.py
  /home/ubuntu/kg2-build/drugcentral/drugcentral_psql_json.json /home/ubuntu/kg2-build/kg2-drugce
ntral.json
        (exited with non-zero exit code)
```

_Originally posted by @acevedol in https://github.com/RTXteam/RTX-KG2/issues/226#issuecomment-1238434439_

**Comment by acevedol** [comment]
Resolved with commit `https://github.com/RTXteam/RTX-KG2/commit/7b66e88b670684bd7f658c0d7313e301ab49946d`
