### ISSUE TITLE
Error in rule Ontologies_and_TTL

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#236]
```
Error in rule Ontologies_and_TTL:
    jobid: 7
    output: /home/ubuntu/kg2-build/kg2-ont.json
    log: /home/ubuntu/kg2-build/build-multi-ont-kg.log (check log file(s) for error message)
    shell:
        bash -x /home/ubuntu/kg2-code/build-multi-ont-kg.sh /home/ubuntu/kg2-build/umls_cuis.tsv /home/ubuntu/kg2-build/kg2-ont.json  > /home/ubuntu/kg2-build/build-multi-ont-kg.log 2>&1
        (exited with non-zero exit code)
```

**Comment by acevedol** [comment]
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1340, in <module>
    delete_ontobio_cachier_caches()
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 59, in delete_ontobio_cachier_caches
    kg2_util.purge("~/.cachier", ".ontobio*")
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 334, in purge
    for f in os.listdir(exp_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.cachier'
```

**Comment by acevedol** [comment]
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1364, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 143, in make_kg2
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 67, in load_ont_file_return_ontology_and_metadata
    ontology = kg2_util.make_ontology_from_local_file(file_name, save_pickle=save_pickle)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 802, in make_ontology_from_local_file
    check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['owltools', 'foodon.owl', '-o', '-f', 'json', '/tmp/kg2-vn_ibfzz.json']' returned non-zero exit status 1.
```

**Comment by acevedol** [comment]
Downloaded foodon-0.5.1 and extracted foodon.owl. Temporarily setting foodon to "do not download" in ont inventory list.

**Comment by acevedol** [comment]
```
Reading ontology JSON file: umls-mth.json; size: 305367.34 KiB
file: umls-mth.ttl; last modified: 2022-09-09 19:59:34 GMT
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1367, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 134, in make_kg2
    if ont_source_info_dict['download']:
TypeError: 'NoneType' object is not subscriptable
```
