### ISSUE TITLE
Error in rule DrugCentral_Conversion

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#237]
```
Error in rule DrugCentral_Conversion:
    jobid: 23
    output: /home/ubuntu/kg2-build/kg2-drugcentral.json
    shell:
        /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/drugcentral_j
son_to_kg_json.py  /home/ubuntu/kg2-build/drugcentral/drugcentral_psql_json.json
 /home/ubuntu/kg2-build/kg2-drugcentral.json
        (exited with non-zero exit code)
```

**Comment by acevedol** [comment]
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/drugcentral_json_to_kg_json.py", line 298, in <module>
    nodes = make_nodes(json_data['drugcentral_ids'], update_date)
  File "/home/ubuntu/kg2-code/drugcentral_json_to_kg_json.py", line 257, in make_nodes
    name = reformatted_json[node_id]['name']
KeyError: 'name'
```

**Comment by acevedol** [comment]
Rule completed successfully
