### ISSUE TITLE
Error in rule Reactome_Conversion

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#238]
```
Error in rule Reactome_Conversion:
    jobid: 20
    output: /home/ubuntu/kg2-build/kg2-reactome.json
    log: /home/ubuntu/kg2-build/reactome-mysql-to-kg-json.log (check log file(s)
 for error message)
    shell:
        /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/reactome_mysq
l_to_kg_json.py  /home/ubuntu/kg2-build/mysql-config.conf reactome /home/ubuntu/
kg2-build/kg2-reactome.json > /home/ubuntu/kg2-build/reactome-mysql-to-kg-json.l
og 2>&1
```

**Comment by acevedol** [comment]
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/reactome_mysql_to_kg_json.py", line 954, in <modul
e>
    nodes = get_nodes(connection, args.test)
  File "/home/ubuntu/kg2-code/reactome_mysql_to_kg_json.py", line 318, in get_no
des
    for result in run_sql(nodes_sql, connection):
  File "/home/ubuntu/kg2-code/reactome_mysql_to_kg_json.py", line 62, in run_sql
    cursor.execute(sql)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/cursors.py", l
ine 328, in _query
    conn.query(q)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py
", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py
", line 732, in _read_query_result
    result.read()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py
", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py
", line 684, in _read_packet
    packet.check_error()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/protocol.py",
line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/err.py", line
109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'reactome.StableIdentifier' doesn't
exist")
```

**Comment by acevedol** [comment]
Successfully produced kg2-reactome.json
