### ISSUE TITLE
Error in multi ont

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#239]
```
2022-09-27 18:43:44,566 ERROR (OWLAnnotationPropertyTransformer:98) Attempt to transform an axiom to correct misuse of properties failed. Property replacement: {<http://purl.org/pav/version>=<http://purl.org/pav/version>, <https://w3id.org/biolink/vocab/opposite_of>=<https://w3id.org/biolink/vocab/opposite_of>, rdfs:label=rdfs:label}, axiom: AnnotationAssertion(rdfs:label <https://w3id.org/biolink/vocab/GeneOrGeneProductOrChemicalEntityAspectEnum#metabolic+processing> "metabolic processing"), error: class uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplNoCompression cannot be cast to class org.semanticweb.owlapi.model.IRI (uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplNoCompression and org.semanticweb.owlapi.model.IRI are in unnamed module of loader 'app')
```

**Comment by acevedol** [comment]
Failing error 
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1367, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 180, in make_kg2
    select_datatype_properties) # temporary addition for Ontobio Issue #507
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 718, in make_nodes_dict_from_ontologies_list
    bpv_pred_curie = convert_bpv_pred_to_curie_func(bpv_pred)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1324, in <lambda>
    curie_expander)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1315, in convert_bpv_predicate_to_curie
    raise ValueError('unable to expand CURIE: ' + bpv_pred)
ValueError: unable to expand CURIE: ttp://www.geneontology.org/formats/oboInOwl#created_by
```

**Comment by acevedol** [comment]
That curie is clearly not right, but I don't see it in our code yet

**Comment by acevedol** [comment]
Found typo with help from Steve, in cell ontology. Updated `cl.owl`, tested with only cl, and restarted Ontologies and TTL
