### ISSUE TITLE
Error in rule Stats:

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#240]
```
[Wed Sep 28 16:15:14 2022]
Error in rule Stats:
    jobid: 2
    output: /home/ubuntu/kg2-build/kg2-report.json
    shell:
        /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/report_stats_on_json_kg.py /home/ubuntu/kg2-build/kg2.json /home/ubuntu/kg2-build/kg2-report.json
        (exited with non-zero exit code)

```

**Comment by acevedol** [comment]
This error occurred while building a small, test kg2 with only Biolink and Chembl

**Comment by acevedol** [comment]
```
    return collections.Counter([edge[curie_field] for edge in edges])
  File "/home/ubuntu/kg2-code/report_stats_on_json_kg.py", line 96, in <listcomp>
    return collections.Counter([edge[curie_field] for edge in edges])
KeyError: 'original_predicate'
```

**Comment by acevedol** [comment]
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/report_stats_on_json_kg.py", line 195, in <module>
    json.dump(stats, outfile, indent=4, sort_keys=True)
  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 353, in _iterencode_dict
    items = sorted(dct.items(), key=lambda kv: kv[0])
TypeError: '<' not supported between instances of 'str' and 'NoneType
```
