### ISSUE TITLE
Error in rule Simplify

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#242]
```
Processing edge 62000000 out of 62037257
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/filter_kg_and_remap_predicates.py", line 257, in <module>
    qualified_predicate_object_direction)
  File "/home/ubuntu/kg2-code/filter_kg_and_remap_predicates.py", line 58, in update_edge_id
    assert len(value_list) == 4
AssertionError
```

**Comment by acevedol** [comment]
Error
```
original predicate curie is missing from the YAML config file: NCIT:has_pcdc_aml_permissible_value
original predicate curie is missing from the YAML config file: RO:0019000
original predicate curie is missing from the YAML config file: NCIT:is_pcdc_all_permissible_value_for_variable
original predicate curie is missing from the YAML config file: NCIT:is_seronet_permissible_value_for_variable
original predicate curie is missing from the YAML config file: RO:0019002
original predicate curie is missing from the YAML config file: NCIT:icdc_value_of
original predicate curie is missing from the YAML config file: linkml:examples
original predicate curie is missing from the YAML config file: BSPO:0020001
original predicate curie is missing from the YAML config file: RO:0007001
original predicate curie is missing from the YAML config file: NCIT:pcdc_data_type_of
original predicate curie is missing from the YAML config file: RO:0019001
original predicate curie is missing from the YAML config file: RO:0015012
original predicate curie is missing from the YAML config file: RO:0000081
original predicate curie is missing from the YAML config file: NCIT:is_pcdc_aml_permissible_value_for_variable
original predicate curie is missing from the YAML config file: NCIT:value_set_is_paired_with
original predicate curie is missing from the YAML config file: NCIT:has_pcdc_gct_permissible_value
original predicate curie is missing from the YAML config file: LOINC:has_maneuver_type
original predicate curie is missing from the YAML config file: NCIT:is_pcdc_gct_permissible_value_for_variable
original predicate curie is missing from the YAML config file: NCIT:has_pcdc_data_type
original predicate curie is missing from the YAML config file: DrugCentral:other
original predicate curie is missing from the YAML config file: RO:0015015
original predicate curie is missing from the YAML config file: RO:0015016
original predicate curie is missing from the YAML config file: linkml:local_names
original predicate curie is missing from the YAML config file: NCIT:may_be_normal_tissue_origin_of_disease
original predicate curie is missing from the YAML config file: NCIT:is_ctdc_value_of
original predicate curie is missing from the YAML config file: LOINC:is_maneuver_type_for
original predicate curie is missing from the YAML config file: RO:0004003
original predicate curie is missing from the YAML config file: NCIT:has_seronet_permissible_value
original predicate curie is missing from the YAML config file: NCIT:has_gdc_value
original predicate curie is missing from the YAML config file: RO:0015011
original predicate curie is missing from the YAML config file: RO:0015010
original predicate curie is missing from the YAML config file: RO:0004004
original predicate curie is missing from the YAML config file: NCIT:is_pcdc_ews_permissible_value_for_variable
original predicate curie is missing from the YAML config file: NCIT:has_icdc_value
original predicate curie is missing from the YAML config file: RO:0015007
original predicate curie is missing from the YAML config file: NCIT:has_pcdc_all_permissible_value
original predicate curie is missing from the YAML config file: NCIT:has_pcdc_ews_permissible_value
original predicate curie is missing from the YAML config file: NCIT:is_value_for_gdc_property
original predicate curie is missing from the YAML config file: NCIT:disease_may_have_normal_tissue_origin
original predicate curie is missing from the YAML config file: RO:0013007
original predicate curie is missing from the YAML config file: NCIT:has_ctdc_value
original predicate curie is missing from the YAML config file: NCIT:is_paired_with_value_set
original predicate curie is missing from the YAML config file: RO:0015008
There are original predicate curies missing from the yaml config file. Please add them and try again. Exiting.
```

**Comment by acevedol** [comment]
Simplify completed 
```
Processing edge 62000000 out of 62037257
{'timestamp_utc': '2022-10-19 02:01', 'version': 'RTX KG2.8.0'}
+ aws s3 cp --no-progress --region us-west-2 /home/ubuntu/kg2-build/kg2-version.txt s3://rtx-kg2-public/kg2-version.txt
upload: kg2-build/kg2-version.txt to s3://rtx-kg2-public/kg2-version.txt
+ [[ -f /home/ubuntu/kg2-build/major-release ]]
+ date
Wed Oct 19 03:50:23 UTC 2022
+ echo '================= finishing run-simplify.sh =================='
================= finishing run-simplify.sh ==================
```
