### ISSUE TITLE
Report Script is Not Behaving As Expected

### ISSUE THREAD

**Issue by ecwood** [RTXteam/RTX-KG2#287]
After the updates from #263, the report script does not seem to be working as intended.

I attempted a fix here: [172fedc](https://github.com/RTXteam/RTX-KG2/commit/172fedce38acd5e411a8a84ac9bc036f4c1a004a) but it did not quite work (see https://github.com/RTXteam/RTX-KG2/issues/276#issuecomment-1599649016).

**Comment by ecwood** [comment]
Here was the original error:
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/report_stats_on_json_kg.py", line 181, in <module>
    'number_of_nodes_by_source': dict(count_nodes_by_source(nodes)),
  File "/home/ubuntu/kg2-code/report_stats_on_json_kg.py", line 70, in count_nodes_by_source
    return collections.Counter([node.get(label_field) for node in nodes])
  File "/usr/lib/python3.7/collections/__init__.py", line 568, in __init__
    self.update(*args, **kwds)
  File "/usr/lib/python3.7/collections/__init__.py", line 655, in update
    _count_elements(self, iterable)
TypeError: unhashable type: 'list'
```

**Comment by ecwood** [comment]
While I'm working on this, I am going to add a few other features based on
#58 (report on orphan nodes)
An old issue (that I can't find) about documenting the version of each source in the build
The build version number/datetime (it will make it easier to keep track of what reports go to what
https://github.com/RTXteam/RTX-KG2/issues/256#issuecomment-1453850374

**Comment by ecwood** [comment]
This is fixed as of `KG2.8.4pre`, so I am going to close out this issue.
