### ISSUE TITLE
KGX Build Error

### ISSUE THREAD

**Issue by ecwood** [RTXteam/RTX-KG2#288]
![image](https://github.com/RTXteam/RTX-KG2/assets/36611732/be6e460d-2c7a-46d3-908e-2390a92ec60f)

**Comment by acevedol** [comment]
`(venv) ubuntu@ip-172-31-50-177:~$ python3.7 -u ~/kg2-code/kg2_json_to_kgx_tsv.py ~/kg2-build/kg2-simplified.json ~/kg2-build/KGX/
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/kg2_json_to_kgx_tsv.py", line 128, in <module>
    for item in nodes_data:
  File "/home/ubuntu/kg2-code/kg2_json_to_kgx_tsv.py", line 110, in <genexpr>
    nodes_data = (row for row in ijson.items(input_file, "nodes.item"))
ijson.common.IncompleteJSONError: parse error: premature EOF
`

**Comment by ShannonRanio** [comment]
@hodgesf another possible stalled issue.

**Comment by hodgesf** [comment]
Not exactly sure what the issue here is, but this is no longer relevant to KG2103. Closing.
