### ISSUE TITLE
Reactome Conversion Script Fails

### ISSUE THREAD

**Issue by ecwood** [RTXteam/RTX-KG2#297]
While testing for #296, I found that `reactome_mysql_to_kg_json.py` fails:

```
/home/ubuntu/kg2-venv/lib/python3.7/site-packages/rdflib_jsonld/__init__.py:12: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  DeprecationWarning,
Traceback (most recent call last):
  File "reactome_mysql_to_kg_json.py", line 954, in <module>
    nodes = get_nodes(connection, args.test)
  File "reactome_mysql_to_kg_json.py", line 318, in get_nodes
    for result in run_sql(nodes_sql, connection):
  File "reactome_mysql_to_kg_json.py", line 62, in run_sql
    cursor.execute(sql)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'reactome.stableidentifier' doesn't exist")
```

It's likely that the schema for Reactome has changed.

**Comment by ecwood** [comment]
I contacted Reactome about this difference. This was their response:

> We are planning to retire the summation attribute in the Regulation class. Summation objects annotated in Regulations have been migrated to ReactionlikeEvents those Regulations regulate to consolidate annotations around ReactionlikeEvent objects. The actual table used is Event_2_summation since Event is a super class to ReactionlikeEvent.

**Comment by ecwood** [comment]
With [778ac1e](https://github.com/RTXteam/RTX-KG2/commit/778ac1e9fe10f5b43ee28c28432155ac9bbd0ebc) and [1503bd6](https://github.com/RTXteam/RTX-KG2/commit/1503bd62a5c2083a385cb4bd44879213ae067837), the script seems to be working again. Here is an example edge with the publications information working:

```
        {
            "id": "REACT:R-ALL-112275---REACT:positively_regulates---None---None---None---REACT:R-HSA-622390---identifiers_org_registry:reactome",
            "negated": false,
            "object": "REACT:R-HSA-622390",
            "predicate": null,
            "primary_knowledge_source": "identifiers_org_registry:reactome",
            "publications": [
                "PMID:12857742",
                "PMID:18471901"
            ],
            "publications_info": {
                "PMID:12857742": {
                    "sentence": "Netrin-1, through its activation of DCC, triggers TRPC channel mediating the Ca+2 influx that is required for the growth cone turning. The effect of netrin-1 on TRP currents in the neurons is studied in Xenopus. In cultured Xenopus spinal neurons, Netrin-1 evoked Ca+2 influx and a depolarizing, TRPC-like current in both soma and growth cones. Inhibition of the Xenopus homologue of mammalian TRPC1 (XTRPC1) prevented Ca+2 influx, TRPC-like current activation and the chemotropic turning of the growth cone in response to a gradient of Netrin-1.<br>Netrin-1 receptor signalling to TRPC channels is mediated via hydrolysis of PIP2 by PLCgamma which then activates TRPC channel activity through IP3 and DAG."
                },
                "PMID:18471901": {
                    "sentence": "Netrin-1, through its activation of DCC, triggers TRPC channel mediating the Ca+2 influx that is required for the growth cone turning. The effect of netrin-1 on TRP currents in the neurons is studied in Xenopus. In cultured Xenopus spinal neurons, Netrin-1 evoked Ca+2 influx and a depolarizing, TRPC-like current in both soma and growth cones. Inhibition of the Xenopus homologue of mammalian TRPC1 (XTRPC1) prevented Ca+2 influx, TRPC-like current activation and the chemotropic turning of the growth cone in response to a gradient of Netrin-1.<br>Netrin-1 receptor signalling to TRPC channels is mediated via hydrolysis of PIP2 by PLCgamma which then activates TRPC channel activity through IP3 and DAG."
                }
            },
            "qualified_object_aspect": null,
            "qualified_object_direction": null,
            "qualified_predicate": null,
            "relation_label": "positively_regulates",
            "source_predicate": "REACT:positively_regulates",
            "subject": "REACT:R-ALL-112275",
            "update_date": null
        },
```

**Comment by ecwood** [comment]
I am closing this issue because the code worked in `KG2.8.4pre`'s build.
