### ISSUE TITLE
Issue with `ordo.owl` URL

### ISSUE THREAD

**Issue by ecwood** [RTXteam/RTX-KG2#343]
While running a build (in order to test out #339) on an `r5a.4xlarge` instance using the merged code, I ran into this issue:

```
http://purl.obolibrary.org/obo/cl.owl
Reading ontology file: cl.owl; size: 53949.34 KiB
/usr/bin/java -Xms2G -Xmx124G -DentityExpansionLimit=4086000 -Djava.awt.headless=true -classpath /home/ubuntu/kg2-build/owltools owltools.cli.CommandLineInterface cl.owl -o -f json /tmp/kg2-j7dhz18n.json
Reading ontology JSON file: cl.json; size: 30993.82 KiB
file: cl.owl; last modified: 2023-08-04 04:52:54 GMT
http://purl.obolibrary.org/obo/foodon.owl
Reading ontology file: foodon.pickle; size: 40463.44 KiB
file: foodon.owl; last modified: 2023-08-04 04:53:38 GMT
http://data.bioontology.org/ontologies/ORDO/submissions/15/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_kg_jsonl.py", line 1400, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_kg_jsonl.py", line 145, in make_kg2
    ont_source_info_dict['file'])
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 682, in download_file_if_not_exist_locally
    with urllib.request.urlopen(url, context=ctx) as u, open(temp_file_name, 'wb') as f:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity
```

_Originally posted by @ecwood in https://github.com/RTXteam/RTX-KG2/issues/321#issuecomment-1665107047_

**Comment by ecwood** [comment]
It appears that URL is no longer available and this is the correct one now:

https://data.bioontology.org/ontologies/ORDO/submissions/27/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb

(Source: https://bioportal.bioontology.org/ontologies/ORDO)

**Comment by ecwood** [comment]
This was actually fixed in the `KG2.8.5pre` build by downloaded `ordo.owl` from kg2erica.rtx.ai onto the build instance.
