### ISSUE TITLE
Error in Ontologies_Conversion

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#360]
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_kg_jsonl.py", line 1277, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_kg_jsonl.py", line 147, in make_kg2
  
  save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_kg_jsonl.py", line 71, in load_ont_fi
le_return_ontology_and_metadata
    ontology = kg2_util.make_ontology_from_local_file(file_name, save_pickle=sav
e_pickle)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 871, in make_ontology_from_local
_file
    check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['owltools', 'umls-nci.ttl', '-o', '-f',
 'json', '/tmp/kg2-1aer0nim.json']' returned non-zero exit status 1.

**Comment by acevedol** [comment]
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_kg_jsonl.py", line 1277, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_kg_jsonl.py", line 147, in make_kg2
  
  save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_kg_jsonl.py", line 71, in load_ont_fi
le_return_ontology_and_metadata
    ontology = kg2_util.make_ontology_from_local_file(file_name, save_pickle=sav
e_pickle)
  File "/home/ubuntu/RTX-KG2/kg2_util.py", line 871, in make_ontology_from_local
_file
    check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['owltools', 'umls-nci.ttl', '-o', '-f',
 'json', '/tmp/kg2-1aer0nim.json']' returned non-zero exit status 1.

**Comment by acevedol** [comment]
Reading ontology file: umls-nci.ttl; size: 39.51 KiB
[Fatal Error] :25:43: The reference to entity "l" must end with the ';' delimiter.

**Comment by saramsey** [comment]
This work is being done on `kg290build.rtx.ai`

**Comment by saramsey** [comment]
This instance is running Ubuntu 22.04
