### ISSUE TITLE
Error in Reactome Conversion

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#371]
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/reactome_mysql_to_kg_jsonl.py", line 933, in <module>
    get_nodes(connection, nodes_output, test_mode)
  File "/home/ubuntu/kg2-code/reactome_mysql_to_kg_jsonl.py", line 323, in get_nodes
    for result in run_sql(nodes_sql, connection):
  File "/home/ubuntu/kg2-code/reactome_mysql_to_kg_jsonl.py", line 69, in run_sql
    cursor.execute(sql)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'reactome.Regulation_2_summation' doesn't exist")
```

Reactome changed their table structure recently and the `Regulation_2_summation` table no longer exists

**Comment by saramsey** [comment]
Per Slack DM thread, the plan is to find the most recent Reactome release that does not trigger the above problem, and use that release for building KG2.9.0pre.

Then, after the KG2.9.0pre build is done, we can revisit fixing the Reactome ETL script to address this problem.

**Comment by acevedol** [comment]
Fixed in KG2.9.1 build
